# Generated by Django 3.2.9 on 2022-04-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beach_manager', '0002_alter_beach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_waste', models.TextField()),
                ('num_residues', models.IntegerField()),
                ('pickup_date', models.DateTimeField()),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polluted_beach', to='beach_manager.beach')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beach_manager.beach')),
            ],
            options={
                'verbose_name_plural': 'Garbage Collection',
            },
        ),
    ]
