# Generated by Django 3.2.9 on 2022-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
